// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4gl_b6Jp3zrbzM2bA1QUODkZfnYh8ns',
    appId: '1:73936119828:web:c831745a0cba0d7c3f1f01',
    messagingSenderId: '73936119828',
    projectId: 'jumpcoachaiauth',
    authDomain: 'jumpcoachaiauth.firebaseapp.com',
    storageBucket: 'jumpcoachaiauth.firebasestorage.app',
    measurementId: 'G-WXYPELEJSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCptAN1WjFRpLvA76k4ZMNQL-gg_TpGahc',
    appId: '1:73936119828:android:0cbf69145dc267a23f1f01',
    messagingSenderId: '73936119828',
    projectId: 'jumpcoachaiauth',
    storageBucket: 'jumpcoachaiauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGhBrM5bXe9Jz3L7nTzEOBl8cOxfW8J4',
    appId: '1:73936119828:ios:619817766231466d3f1f01',
    messagingSenderId: '73936119828',
    projectId: 'jumpcoachaiauth',
    storageBucket: 'jumpcoachaiauth.firebasestorage.app',
    iosBundleId: 'com.example.jumpCoachAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcGhBrM5bXe9Jz3L7nTzEOBl8cOxfW8J4',
    appId: '1:73936119828:ios:619817766231466d3f1f01',
    messagingSenderId: '73936119828',
    projectId: 'jumpcoachaiauth',
    storageBucket: 'jumpcoachaiauth.firebasestorage.app',
    iosBundleId: 'com.example.jumpCoachAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4gl_b6Jp3zrbzM2bA1QUODkZfnYh8ns',
    appId: '1:73936119828:web:0e7901883b333c293f1f01',
    messagingSenderId: '73936119828',
    projectId: 'jumpcoachaiauth',
    authDomain: 'jumpcoachaiauth.firebaseapp.com',
    storageBucket: 'jumpcoachaiauth.firebasestorage.app',
    measurementId: 'G-NJ11L2FCQT',
  );
}
